spring:
  datasource:
    drivenClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quiz
    username: root
    password: App12345
  jpa:
    hibernate.dll-auto: update
    generate-ddl: true
    show-sql: true
