spring:
  datasource:
    drivenClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quiz_quarter
    username: root
    password: mara
  jpa:
    hibernate.dll-auto: update
    generate-ddl: true
    show-sql: true
